/**
 * Conversation compaction — DTO-space helpers.
 *
 * Compaction operates on the panel's ChatMessageDTO history (stable ids,
 * tool results inline) rather than on converted ModelMessages, for two
 * structural guarantees:
 *
 *   1. PAIRING — an assistant DTO carries its tool calls WITH their results
 *      inline; folding whole DTOs and cutting only where the kept slice
 *      starts with a `user` DTO makes it impossible to separate a
 *      `tool_use` from its `tool_result` (the old index-split could, and
 *      Anthropic rejects unpaired results with a 400).
 *   2. PERSISTENCE — DTO ids let the compaction cache store a cursor
 *      ("everything up to id X is folded into this summary") that stays
 *      valid across turns even though the panel resends the full history.
 *
 * The summary itself is generated by `runner.ts` (fast model) using
 * `buildSummaryRequest`; multipart messages are flattened faithfully via
 * `flattenDtoForSummary` — tool name + compact args + result excerpt —
 * instead of the old information-free `'[multipart]'` placeholder.
 *
 * This module exposes pure helpers; the runner integrates them.
 */

import { estimateDtoTokens } from './token-estimate.js';
import type { CompactionCacheRecord } from './compaction-cache.js';
import type { ChatMessageDTO, MessagePartDTO } from './conversion.js';
import type { ModelMessage } from 'ai';

/** Per-part caps for the summary input — keep the fold request itself cheap. */
const SUMMARY_TEXT_CAP = 2_000;
const SUMMARY_ARGS_CAP = 300;
const SUMMARY_RESULT_CAP = 400;

/**
 * Split the full panel history at the persisted cursor. `cursorValid:false`
 * means the record is unusable (id vanished — mid-history edit or a
 * different conversation — or there is no tail after it) and the caller
 * should drop the record and recompact from the full history.
 */
export function splitByCursor(
  messages: ChatMessageDTO[],
  record: CompactionCacheRecord | null,
): { tail: ChatMessageDTO[]; cursorValid: boolean } {
  if (!record) return { tail: messages, cursorValid: false };
  const idx = messages.findIndex(m => m.id === record.cursorMessageId);
  if (idx === -1 || idx >= messages.length - 1) return { tail: messages, cursorValid: false };
  return { tail: messages.slice(idx + 1), cursorValid: true };
}

/**
 * Pick the fold boundary: everything before index `boundary` gets
 * summarized, `tail.slice(boundary)` survives verbatim.
 *
 * Invariants:
 *   - the kept slice always starts with a `user` DTO (walk back from the
 *     end accumulating tokens until the keep budget is exceeded, then snap
 *     FORWARD to the nearest user boundary);
 *   - the last user DTO and everything after it always survive;
 *   - returns 0 (= no-op) when nothing can be safely folded.
 */
export function selectCompactionBoundary(tail: ChatMessageDTO[], keepBudgetTokens: number): number {
  if (tail.length === 0) return 0;

  let lastUserIdx = -1;
  for (let i = tail.length - 1; i >= 0; i--) {
    if (tail[i].role === 'user') {
      lastUserIdx = i;
      break;
    }
  }
  // No user message, or it's already first — nothing safely foldable.
  if (lastUserIdx <= 0) return 0;

  let kept = 0;
  let candidate = 0;
  for (let i = tail.length - 1; i >= 0; i--) {
    kept += estimateDtoTokens(tail[i]);
    if (kept > keepBudgetTokens) {
      candidate = i + 1;
      break;
    }
  }
  // Everything fits inside the keep budget — no fold needed.
  if (candidate === 0) return 0;

  // Snap forward to a user boundary, never past the always-keep zone.
  for (let i = candidate; i <= lastUserIdx; i++) {
    if (tail[i].role === 'user') return i;
  }
  return lastUserIdx;
}

/**
 * Faithful single-line-per-part flattening for the summary input. The old
 * code serialized every multipart message as the literal '[multipart]',
 * which made summaries of tool-heavy histories information-free.
 */
export function flattenDtoForSummary(message: ChatMessageDTO): string {
  const lines: string[] = [];
  for (const p of message.parts) {
    if (p.kind === 'text' && typeof p.text === 'string' && p.text.trim().length > 0) {
      lines.push(excerpt(p.text, SUMMARY_TEXT_CAP));
    } else if (p.kind === 'image') {
      lines.push('[screenshot]');
    } else if (p.kind === 'tool_call' || p.kind === 'tool_result') {
      lines.push(flattenToolPart(p));
    }
  }
  return `${message.role}: ${lines.join('\n') || '(empty)'}`;
}

function flattenToolPart(p: MessagePartDTO): string {
  const name = p.toolName ?? 'tool';
  const args = p.args === undefined ? '' : excerpt(p.args, SUMMARY_ARGS_CAP);
  const result = flattenToolResult(p.result);
  return `tool ${name}(${args})${result ? ` -> ${result}` : ''}`;
}

function flattenToolResult(result: unknown): string {
  if (result === undefined || result === null) return '';
  if (typeof result === 'object' && '__doe_image' in result) {
    const { __doe_image: _image, ...rest } = result;
    const meta = Object.keys(rest).length > 0 ? ` ${excerpt(rest, SUMMARY_RESULT_CAP)}` : '';
    return `[screenshot]${meta}`;
  }
  return excerpt(result, SUMMARY_RESULT_CAP);
}

function excerpt(value: unknown, cap: number): string {
  const s = typeof value === 'string' ? value : safeStringify(value);
  return s.length > cap ? `${s.slice(0, cap)}…` : s;
}

function safeStringify(value: unknown): string {
  try {
    return JSON.stringify(value) ?? String(value);
  } catch {
    return String(value);
  }
}

/**
 * Build the fast-model summary request. With a previous summary the model
 * MERGES (update-to-also-cover) instead of regenerating from scratch, so
 * facts folded turns ago survive later folds.
 */
export function buildSummaryRequest(opts: { previousSummary: string | null; toFold: ChatMessageDTO[] }): {
  system: string;
  prompt: string;
} {
  const system =
    'You are summarising an doeverything browser-agent conversation so the agent can keep working without ' +
    'exceeding its context window. Be tight and faithful: 6-14 bullet points capturing the user\'s goals, ' +
    'decisions made, key facts and data discovered (URLs, names, numbers, extracted content), actions already ' +
    'performed, and the current task state. Do not add commentary.';
  const exchange = opts.toFold.map(flattenDtoForSummary).join('\n\n');
  const prompt = opts.previousSummary
    ? `Existing summary of the conversation so far:\n${opts.previousSummary}\n\n` +
      `Update the existing summary so it ALSO covers the new exchange below. Keep every still-relevant fact ` +
      `from the existing summary; drop only what the new exchange makes obsolete.\n\nNew exchange:\n\n${exchange}`
    : `Summarise the following exchange:\n\n${exchange}`;
  return { system, prompt };
}

/**
 * The stable summary message — ALWAYS messages[0] of the model
 * conversation once compaction is active. The wording is frozen and the
 * summary string is reused verbatim across turns, so this message is
 * byte-identical between folds and the provider's prompt-cache prefix
 * survives. (As a leading system message it sits directly after the
 * instructions message, which carries the static cache breakpoint.)
 */
export function buildSummaryMessage(summary: string): ModelMessage {
  return {
    role: 'system',
    content: `[Earlier conversation summary]\n${summary}`,
  };
}
