blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/tufanYavas/doeverything/discussions
    about: Ask questions and discuss doeverything in GitHub Discussions.
