name: Format Check

on: [pull_request_target]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Prettier
        id: prettier-run
        uses: rutajdash/prettier-cli-action@v1.0.2
        with:
          config_path: ./.prettierrc
          file_pattern: "*.{js,jsx,ts,tsx,json}"
      - name: Show unformatted files
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "The following files are not formatted:"
          echo "${{ steps.prettier-run.outputs.prettier_output }}"
